{
    "name" : "Print Report",
    "version" : "1.0",
    "depends" : ["base","request_requisition"],
    "author" : "wibicon.com",
    "category" : "Education",
    "website" : "www.wibicon.com",
    "description" : "Addons Report",
    "data" : [
        "reports/print_rr.xml",
        "reports/print_purchase_request_1.xml",
        "reports/print_purchase_request_bb.xml",
        "reports/print_lpb.xml",
        "reports/print_pengeluaran.xml",
        "views/request_requisition.xml",
    ],
    "installable" : True,
    "auto-install" : False,
    "application" : True,
}