{
    'name': "Inherit Mrp",
    'version': '1.0',
    'depends': ['base', 'mrp', 'base_master','test_development','labdip','inherit_sale_order','inherit_product'],
    'author': "Wibicon",
    'category': 'Category',
    'description': """
    Description text
    """,
    # data files always loaded at installation
    'data': [
        'wizard/reprocess_wo_wizard.xml',
        'data/ir.sequence.xml',
        'data/mrp_shrinkage.xml',
        'security/ir.model.access.csv',
        'security/security.xml',
        'views/mrp_bom.xml',
        'views/mrp_production.xml',
        'views/mrp_type.xml',
        'views/product_template.xml',
        'views/mrp_routing_workcenter.xml',
        'views/mrp_workorder.xml',
        'views/master_flow_proses.xml',
        'views/mrp_production_sizing.xml',
        'views/mrp_production_twisting_tfo.xml',
        'views/mrp_production_twisting_ity.xml',
        'views/mrp_production_weaving.xml',
        'views/mrp_production_warping.xml',
        'views/mrp_production_dyeing.xml',
        'views/mrp_production_beam.xml',
        'views/mrp_production_planning.xml',
        'views/test_development.xml',
        'views/permintaan_kain.xml',
        'views/mrp_production_papertube.xml',
        'views/mrp_machine.xml',
        'views/mrp_shrinkage.xml',
        'views/product.xml',
        'views/mrp_program.xml',
        'views/mrp_workcenter.xml',
        'views/stock_picking.xml',
        # 'wizard/bon_permintaan_kain.xml',
        'wizard/laporan_papertube.xml',
        'wizard/laporan_produksi_dyeing.xml',
        'wizard/sort_workorder.xml',
        'report/mrp_bom.xml',
        'report/jo_sizing.xml',
        'report/jo_weaving.xml',
        'report/jo_twisting.xml',
        'report/components_planning_request.xml',
        'report/bon_permintaan_kain.xml',
        'report/permintaan_kain.xml',
        'report/jo_papertube.xml',
        'report/mrp_workcenter.xml',
        'report/print_kartu_proses_new.xml',
        'report/report_produksi_dyeing.xml',
        'report/report_produksi_dyeing_workcenter.xml',
        'report/report_produksi_dyeing_permesin.xml',
        'report/mrp_production_resep.xml',
    ],
}