{
    'name': 'Print Out',
    'version': '0.1.3',
    'author': 'DunDun',
    'category': 'Print Out',
    'depends': [
        'base',
        'stock',
        'account',
        ],
    'summary': 'Print Out',
    'description': """

""",
    'data': [
        # 'security/ir.model.access.csv',
        
        'report/accounting.xml',
        # 'report/kartu_proses.xml',
        # 'report/labdip.xml',
        # 'report/packing_list.xml',
        # 'report/print_kartu_proses_v2.xml',
        # 'report/print_kartu_proses.xml',
        # 'report/print_penerimaan.xml',
        # 'report/print_receipt.xml',
        # 'report/print_release.xml',
        # # 'report/print_release_benang.xml',
        # 'report/purchase_order.xml',
         'report/purchase_request.xml',
        # 'report/sale_contract.xml',
        # 'report/sale_order.xml',
        # 'report/strikeoff.xml',
        # 'report/surat_jalan.xml',
        'report/template_print.xml',
        # 'report/test_development.xml',
        # 'report/work_order.xml',
        # 'report/nota_pesanan.xml',
        # 'report/order_marketing.xml',
        # 'report/pengeluaran_reige.xml',
        # 'report/bukti_penerimaan_greige.xml',
        # 'report/bukti_pengeluaran_greige.xml',
        # 'report/packing_list_pengiriman_kain.xml',
        # 'report/konstruksi_design.xml',
        'report/print_kartu_proses.xml',
        'report/bill_invoice_with_payment.xml',
        'report/bill_invoice_without_payment.xml',
        'report/print_uudp_pengajuan.xml',
        
        
        # 'views/inherit_stock.xml',
        # 'wizard/print_stock_wizard.xml',
    ],
    'installable': True,
    'auto_install': False,
}
